_target_: dccm_quasistatic.utils.sample_generator.SampleGenerator

params:
  _target_: dccm_quasistatic.utils.sample_generator.SampleGeneratorParams
  actuated_collision_geomtery_names: ["hand::collision"]
  n_samples: 100
  workspace_radius: 2
  log_barrier_weight: 100