_target_: dccm_quasistatic.controller.teleop_controller.TeleopController

params:
  _target_: dccm_quasistatic.controller.teleop_controller.TeleopControllerParams
  robot_urdf_path: package://dccm_quasistatic/models/actuated_sphere.urdf
  time_step: 1e-3
  pid_gains:
    kp: 100
    kd: 20
    ki: 1
  teleop:
    input_limit: 10.0
    step_size: 0.1
    start_translation: [0.0, 0.0] # Planar xy position